version: "3.2"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/
    command: python /usr/src/app/app.py
    ports:
      - "5000:5000"
